#include "ui.h"
#include "serial.h" // for logging debug messages

// Mono port: composite a 1bpp canvas onto any GFX target with color-key
// semantics. Pixels whose mono bit differs from the (thresholded) background
// are drawn; matching pixels are skipped, like the old transparent-color draw.
static void drawMonoCanvasTran(
    Arduino_GFX* g, lilka::Canvas* src, int16_t destX, int16_t destY, int16_t w, int16_t h, uint16_t bgColor
) {
    const bool bgBit = bgColor & 0b1000010000010000;
    const uint8_t* fb = src->getFramebuffer();
    const int16_t stride = src->monoStride();
    if (w > src->width()) w = src->width();
    if (h > src->height()) h = src->height();
    for (int16_t y = 0; y < h; y++) {
        const uint8_t* line = fb + y * stride;
        for (int16_t x = 0; x < w; x++) {
            const bool bit = line[x >> 3] & (0x80 >> (x & 7));
            if (bit != bgBit) {
                g->writePixel(destX + x, destY + y, bit ? 0xFFFF : 0x0000);
            }
        }
    }
}

// Composite a packed MonoIconAsset (1bpp color plane + 1bpp mask plane,
// generated by tools/image2code.py --mono) directly onto a GFX target.
// mask bit 0 = fully transparent, skip - real alpha-driven transparency,
// not a magic-color-key convention.
void drawMonoIcon(Arduino_GFX* g, const MonoIconAsset* icon, int16_t destX, int16_t destY) {
    const int16_t stride = (icon->width + 7) / 8;
    for (int16_t y = 0; y < icon->height; y++) {
        const uint8_t* colorLine = icon->color + y * stride;
        const uint8_t* maskLine = icon->mask + y * stride;
        for (int16_t x = 0; x < icon->width; x++) {
            const uint8_t bit = 0x80 >> (x & 7);
            if (!(maskLine[x >> 3] & bit)) continue; // transparent, skip
            const bool white = colorLine[x >> 3] & bit;
            g->writePixel(destX + x, destY + y, white ? 0xFFFF : 0x0000);
        }
    }
}

// Unpack a packed MonoIconAsset into an RGB565 lilka::Image buffer, for the
// ONE place that still genuinely needs RGB565: the cursor's rotating icon
// animation (drawSelectedIcon), which samples per-pixel through Transform/
// drawImageTransformed and can't operate on packed bits directly.
static void unpackIconToImage(const MonoIconAsset* icon, lilka::Image* dest, uint16_t transparentColor) {
    const int16_t w = icon->width < menu_icon_width ? icon->width : menu_icon_width;
    const int16_t h = icon->height < menu_icon_height ? icon->height : menu_icon_height;
    const int16_t stride = (icon->width + 7) / 8;
    for (int16_t y = 0; y < h; y++) {
        const uint8_t* colorLine = icon->color + y * stride;
        const uint8_t* maskLine = icon->mask + y * stride;
        for (int16_t x = 0; x < w; x++) {
            const uint8_t bit = 0x80 >> (x & 7);
            uint16_t px;
            if (!(maskLine[x >> 3] & bit)) {
                px = transparentColor;
            } else {
                px = (colorLine[x >> 3] & bit) ? lilka::colors::White : lilka::colors::Black;
            }
            dest->pixels[y * menu_icon_width + x] = px;
        }
    }
}



namespace lilka {

#define MENU_HEIGHT 5

#define MIN(a, b)   ((a) < (b) ? (a) : (b))

Menu::Menu(const String& title) {
    this->title = title;
    this->scroll = 0;
    this->setCursor(0);
    this->done = false;
    this->iconImage = new Image(menu_icon_width, menu_icon_height, bgColor, menu_icon_width / 2, menu_icon_height / 2);
    this->iconCanvas = new Canvas(menu_icon_width, menu_icon_height);
    this->lastCursorMove = millis();
    this->lastCursorMoveUs = micros();
    this->button = Button::COUNT;
    this->activationButtons.push_back(Button::A);
    this->firstRender = -1;
}

Menu::~Menu() {
    delete iconImage;
    delete iconCanvas;
}
void Menu::setTitle(const String& title) {
    this->title = title;
}
void Menu::addItem(
    const String& title, const menu_icon_t* icon, uint16_t color, const String& postfix, PMenuItemCallback callback,
    void* callbackData
) {
    items.push_back(
        {.title = title,
         .icon = icon,
         .color = color,
         .postfix = postfix,
         .callback = callback,
         .callbackData = callbackData}
    );
}

void Menu::setCursor(int16_t cursor) {
    if (cursor < 0) {
        cursor = items.size() - 1;
    } else if (cursor >= items.size()) {
        cursor = 0;
    }
    this->cursor = cursor;
}

// List-mode cursor movement: UP/DOWN by 1 with wraparound, LEFT/RIGHT pages
// by MENU_HEIGHT. This is exactly the pre-grid update() logic, unchanged,
// just extracted so update() can dispatch to it.
void Menu::updateCursorList(State& state, bool& cursorMoved) {
    auto cursorLastPos = cursor;
    if (state.up.justPressed) {
        if (cursor == 0) {
            cursor = items.size() - 1;
        } else {
            cursor--;
        }
    } else if (state.down.justPressed) {
        cursor++;
        if (cursor >= items.size()) {
            cursor = 0;
        }
    } else if (state.left.justPressed) {
        if (cursor == 0) cursor = items.size() - 1;
        else cursor = (cursor - MENU_HEIGHT) <= 0 ? cursor = 0 : (cursor - MENU_HEIGHT);
    } else if (state.right.justPressed) {
        if (cursor == items.size() - 1) cursor = 0;
        else cursor = (cursor + MENU_HEIGHT) >= items.size() - 1 ? items.size() - 1 : (cursor + MENU_HEIGHT);
    }
    cursorMoved = (cursorLastPos != cursor);
    if (cursor < scroll) {
        scroll = cursor;
    } else if (cursor > scroll + MENU_HEIGHT - 1) {
        scroll = cursor - MENU_HEIGHT + 1;
    }
}

// Grid-mode cursor movement: UP/DOWN jump by gridColumns and wrap to the
// same column on the opposite edge row (clamped if the target row is
// shorter, e.g. a partially-filled last row). LEFT/RIGHT flow in reading
// order (right past the last column advances into the next row, rather
// than clamping at the row edge) - this also means a partially-filled last
// row needs no special-casing for LEFT/RIGHT.
void Menu::updateCursorGrid(State& state, bool& cursorMoved) {
    auto cursorLastPos = cursor;
    int16_t itemCount = items.size();
    if (itemCount == 0) {
        cursorMoved = false;
        return;
    }

    if (state.up.justPressed) {
        int16_t candidate = cursor - gridColumns;
        if (candidate < 0) {
            int16_t lastRowStart = (itemCount - 1) / gridColumns * gridColumns;
            candidate = lastRowStart + (cursor % gridColumns);
            if (candidate >= itemCount) candidate = itemCount - 1;
        }
        cursor = candidate;
    } else if (state.down.justPressed) {
        int16_t totalRows = (itemCount + gridColumns - 1) / gridColumns; // ceiling division
        int16_t cursorRow = cursor / gridColumns;
        int16_t candidate = cursor + gridColumns;
        if (cursorRow == totalRows - 1) {
            // truly on the last row (regardless of what's currently scrolled
            // into view) -> wrap to the top, same column
            cursor = cursor % gridColumns;
        } else if (candidate >= itemCount) {
            // not the last row, but the column below doesn't exist in a
            // ragged final row -> clamp to the last real item
            cursor = itemCount - 1;
        } else {
            cursor = candidate;
        }
    } else if (state.left.justPressed) {
        cursor = (cursor == 0) ? itemCount - 1 : cursor - 1;
    } else if (state.right.justPressed) {
        cursor = (cursor == itemCount - 1) ? 0 : cursor + 1;
    }
    cursorMoved = (cursorLastPos != cursor);

    int16_t cursorRow = cursor / gridColumns;
    int16_t scrollRow = scroll / gridColumns;
    if (cursorRow < scrollRow) {
        scroll = cursorRow * gridColumns;
    } else if (cursorRow > scrollRow + gridVisibleRows - 1) {
        scroll = (cursorRow - gridVisibleRows + 1) * gridColumns;
    }
}

void Menu::update() {
    State state = controller.getState();
    bool cursorMoved = false;

    if (layout == MenuLayout::GRID) {
        updateCursorGrid(state, cursorMoved);
    } else {
        updateCursorList(state, cursorMoved);
    }
    if (cursorMoved) lastCursorMoveUs = micros();

    for (Button activationButton : activationButtons) {
        lilka::_StateButtons& buttonsArray = *reinterpret_cast<lilka::_StateButtons*>(&state);
        if (buttonsArray[activationButton].justPressed) {
            button = activationButton;
            done = true;
            // Should be made after done flag setup to allow to clear it by isFinished() call
            if (items[cursor].callback) { // call callback if
                items[cursor].callback(items[cursor].callbackData);
            }
        }
    }
    vTaskDelay(LILKA_UI_UPDATE_DELAY_MS / portTICK_PERIOD_MS);
}

// Scroll marquee back and forth based on time, pausing at start and end
int16_t calculateMarqueeShift(uint64_t time, uint16_t maxShift, uint16_t pixelsPerSecond) {
    constexpr uint64_t startDelay = 750;
    uint64_t midTime = maxShift * 1000 / pixelsPerSecond;
    constexpr uint64_t endDelay = 750;
    const uint64_t period = startDelay + 2 * midTime + endDelay;
    const uint64_t phase = time % period;

    int16_t shift = 0;
    if (phase < startDelay) {
        // Start delay
        shift = 0;
    } else if (phase < startDelay + midTime) {
        // Scroll
        shift = (phase - startDelay) * pixelsPerSecond / 1000;
    } else if (phase < startDelay + midTime + endDelay) {
        // End delay
        shift = maxShift;
    } else {
        // Scroll back
        shift = maxShift - (phase - startDelay - midTime - endDelay) * pixelsPerSecond / 1000;
    }
    return -shift;
}

// Shared by drawList and drawGrid: draws the cursor's icon inverted, with
// the rotation-wobble animation, at an arbitrary destination point.
void Menu::drawSelectedIcon(Arduino_GFX* canvas, const menu_icon_t* icon, int16_t destX, int16_t destY) {
    // Unpack inverted (transparent pixels become white bg, opaque pixels
    // swap black<->white) so the selected icon reads correctly against the
    // highlight background - real alpha-aware inversion, replaces the old
    // raw-byte-invert trick that only worked because RGB565 0x0000/0xFFFF
    // happened to bit-invert cleanly.
    for (int16_t y = 0; y < menu_icon_height; y++) {
        const int16_t stride = (icon->width + 7) / 8;
        const uint8_t* colorLine = icon->color + y * stride;
        const uint8_t* maskLine = icon->mask + y * stride;
        for (int16_t x = 0; x < menu_icon_width; x++) {
            const uint8_t bit = 0x80 >> (x & 7);
            bool opaque = maskLine[x >> 3] & bit;
            bool whiteInSource = colorLine[x >> 3] & bit;
            iconImage->pixels[y * menu_icon_width + x] =
                (opaque && !whiteInSource) ? lilka::colors::White : lilka::colors::Black;
        }
    }

    // add rotation animation to icon
    // float elapsedMs = (micros() - lastCursorMoveUs) * 0.001f;
    // Transform t = Transform().rotate(sinf(elapsedMs * PI / 1000.0f) * 3.0f);
    // iconCanvas->fillScreen(lilka::colors::White);
    // iconCanvas->drawImageTransformed(iconImage, 12, 12, t);
    // drawMonoCanvasTran(canvas, iconCanvas, destX, destY, menu_icon_width, menu_icon_height, lilka::colors::White); // should be black??!
    float elapsedMs = (micros() - lastCursorMoveUs) * 0.001f;
    Transform t = Transform().rotate(sinf(elapsedMs * PI / 1000.0f) * 3.0f);
    t.scale(1.1, 1.1);
    iconCanvas->fillScreen(lilka::colors::Black);
    iconCanvas->drawImageTransformed(iconImage, 12, 12, t);
    // iconCanvas->drawImage(iconImage, 12, 12);
    drawMonoCanvasTran(canvas, iconCanvas, destX, destY, menu_icon_width, menu_icon_height, lilka::colors::Black);
    
}

void Menu::draw(Arduino_GFX* canvas) {
    if (layout == MenuLayout::GRID) {
        drawGrid(canvas);
    } else {
        drawList(canvas);
    }
}

// Grid layout: gridColumns-wide, gridVisibleRows-tall window of cells, each
// showing an icon with its title centered below. Scrolls by whole rows once
// there are more items than fit in the visible window. Reuses drawList's
// title-bar treatment and drawSelectedIcon's rotation/invert animation for
// visual consistency between the two layouts.
void Menu::drawGrid(Arduino_GFX* canvas) {
    if (this->firstRender == -1) {
        this->firstRender = millis();
    }

    canvas->fillScreen(lilka::colors::White);
    // Temp - replace with drawDithered method when done
    for (int16_t x = 0; x < canvas->width() / 2; x++) {
        for (int16_t y = 0; y < 120; y++) {
            canvas->drawPixel(x * 2, y * 2, lilka::colors::Black);
        };
    };
    // Title bar - same visual treatment as drawList's header.
    constexpr int16_t titleAreaHeight = 0;
    const uint16_t titleWidthAvailable = canvas->width() - 64;
    // canvas->setFont(FONT_5x7);
    // canvas->setTextSize(2);
    // canvas->setCursor(32, 40);
    // canvas->setTextColor(lilka::colors::Black);
    // canvas->setTextBound(32, 8, titleWidthAvailable, 32);
    // canvas->println(title);

    uint16_t menu_size = items.size();
    
    const int16_t cellWidth = 48;
    const int16_t cellHeight = 48;
    const int16_t topPadding = 24;
    const int16_t bottomPadding = 48;
    const int16_t sidePadding = 32;
    const int16_t cellSpacingX = (canvas->width() - sidePadding * 2 - gridColumns * cellWidth) / (gridColumns - 1);
    const int16_t cellSpacingY = (canvas->height() - topPadding - bottomPadding - gridVisibleRows * cellHeight) / (gridVisibleRows - 1);

    // const int16_t cellWidth = (canvas->width() - cellPadding) / gridColumns - cellPadding / gridColumns;
    
    // const int16_t gridAreaHeight = canvas->height() - titleAreaHeight;
    const int16_t gridAreaHeight = canvas->height();
    // const int16_t cellHeight = ((gridAreaHeight - cellPadding) / gridVisibleRows) - cellPadding / gridVisibleRows;
    
    constexpr int16_t highlightRadius = 7;


    int16_t lastVisible = MIN(scroll + gridColumns * gridVisibleRows, (int16_t)menu_size);
    for (int16_t i = scroll; i < lastVisible; i++) {
        int16_t visibleIndex = i - scroll;
        int16_t row = visibleIndex / gridColumns;
        int16_t col = visibleIndex % gridColumns;
        int16_t cellX = sidePadding + col * cellWidth + col * cellSpacingX;
        int16_t cellY = topPadding + row * cellHeight + row * cellSpacingY;
        const menu_icon_t* icon = items[i].icon;
        bool selected = (cursor == i);

        if (selected) {
            // highlight selected
            canvas->fillRoundRect(
                cellX, cellY, cellWidth, cellHeight,
                highlightRadius, lilka::colors::Black
            );
            cellX += 2;
            cellY -= 2;
            canvas->fillRoundRect(
                cellX, cellY, cellWidth, cellHeight,
                highlightRadius, lilka::colors::White
            );
            
            // draw big item text centred bottom
            canvas->setFont(FONT_5x7);
            canvas->setTextSize(2);
            canvas->setTextColor(lilka::colors::Black);
            int16_t bigTextX1, bigTextY1;
            uint16_t bigTextW, bigTextH;
            canvas->getTextBounds(items[i].title, 0, 0, &bigTextX1, &bigTextY1, &bigTextW, &bigTextH);
            canvas->fillRoundRect(
                canvas->width() * 0.5 - 68, canvas->height() - 32, 
                136, 24, 
                7, lilka::colors::White);
            canvas->setCursor(canvas->width() / 2 - bigTextW / 2, canvas->height() - 15);
            canvas->println(items[i].title);
        

            // draw title under selected
            // int16_t xMid = cellX + cellWidth * 0.5; // middle point of selected cell
            // int16_t yMid = cellY + cellHeight;      // base point of selected cell
            // int16_t spacing = 6;
            // int16_t textBoxHeight = 18;
            // canvas->fillRoundRect(
            //     xMid - bigTextW * 0.5 - spacing, 
            //     yMid + spacing, 
            //     bigTextW + spacing * 2, 20, 
            //     5, lilka::colors::White);
            // canvas->setCursor(xMid - bigTextW * 0.5, yMid + textBoxHeight - bigTextH);
            // canvas->setTextColor(lilka::colors::Black);
            // canvas->println(items[i].title);

        } else {
            // draw cell background (will be white when we have wallpaper)
            canvas->fillRoundRect(
                cellX, cellY, cellWidth, cellHeight,
                highlightRadius, lilka::colors::White
            );
        }
        

        int16_t iconX = cellX + (cellWidth / 2) - (menu_icon_width / 2);
        int16_t iconY = cellY + (cellHeight / 2) - (menu_icon_height / 2);
        if (icon) {
            if (selected) {
                canvas->fillRoundRect(
                    iconX - 2, iconY - 2, 
                    menu_icon_width + 4, menu_icon_height + 4,
                    highlightRadius, lilka::colors::Black
                );
                drawSelectedIcon(canvas, icon, iconX, iconY);
            } else {
                drawMonoIcon(canvas, icon, iconX, iconY);
            }
        }

    }
    //     if (textW > textAreaWidth && selected) {
    //         Canvas marquee(textAreaWidth, textH + 4);
    //         marquee.fillScreen(lilka::colors::Black);
    //         marquee.setFont(FONT_5x7);
    //         marquee.setTextSize(1);
    //         marquee.setTextWrap(false);
    //         marquee.setCursor(
    //             calculateMarqueeShift(millis() - lastCursorMoveUs, textW - textAreaWidth, 30), textH
    //         );
    //         marquee.setTextColor(lilka::colors::White);
    //         marquee.println(items[i].title);
    //         drawMonoCanvasTran(
    //             canvas, &marquee, cellX + cellPadding, textY, textAreaWidth, marquee.height(), lilka::colors::Black
    //         );
    //     } else {
    //         canvas->setTextWrap(false);
    //         canvas->setTextBound(cellX, textY, textAreaWidth, textH + 4);
    //         int16_t textX = cellX + (cellWidth - MIN(textW, textAreaWidth)) / 2;
    //         canvas->setCursor(textX, textY);
    //         canvas->println(items[i].title);
    //     }
    // }

    // Scrollbar (vertical), same visual language as drawList's, only shown
    // when there are more rows than fit in the visible window.
    int16_t totalRows = (menu_size + gridColumns - 1) / gridColumns;
    if (totalRows > gridVisibleRows) {
        int16_t top = titleAreaHeight;
        int16_t height = gridAreaHeight;
        canvas->fillRect(canvas->width() - 13, top, 2, height, lilka::colors::Black);
        canvas->fillRect(canvas->width() - 16, top, 8, 2, lilka::colors::Black);
        canvas->fillRect(canvas->width() - 16, top + height - 2, 8, 2, lilka::colors::Black);
        int16_t barHeight = height * gridVisibleRows / totalRows;
        int16_t barTop = top + (scroll / gridColumns) * height / totalRows;
        canvas->fillRect(canvas->width() - 16, barTop, 8, barHeight, lilka::colors::Black);
    }
}

void Menu::drawList(Arduino_GFX* canvas) {
    if (this->firstRender == -1) {
        this->firstRender = millis();
    }

    constexpr int16_t scrollbarWidth = 8;
    constexpr int16_t scrollbarLeftPadding = 4;
    constexpr int16_t postfixLeftPadding = 4;
    constexpr int16_t iconWidth = 32;
    constexpr int16_t titleTextHeight = 32;
    constexpr int16_t itemsY = 64;
    constexpr int16_t itemHeight = menu_item_height;
    uint16_t menu_size = items.size();
    const bool needsScrollbar = menu_size > MENU_HEIGHT;

    // Clear screen and draw graphical decorations
    
    // background
    canvas->fillScreen(lilka::colors::White);
    // Temp - replace with drawDithered method when done
    for (int16_t x = 0; x < canvas->width() / 2; x++) {
        for (int16_t y = 0; y < 120; y++) {
            canvas->drawPixel(x * 2, y * 2, lilka::colors::Black);
        };
    };

    // window
    canvas->fillRect(16, 16, canvas->width() - 32, canvas->height() - 32, lilka::colors::White);
    canvas->drawRect(16, 16, canvas->width() - 32, canvas->height() - 32, lilka::colors::Black);

    // top bar, left square and lines
    canvas->drawRect(16, 16, 368, 208, lilka::colors::Black);
    canvas->fillRect(16, 48, 368, 2, lilka::colors::Black);
    canvas->fillRect(25, 24, 16, 16, lilka::colors::Black);
    canvas->fillRect(27, 26, 12, 12, lilka::colors::White);
    canvas->fillRect(47, 25, 324, 2, lilka::colors::Black);
    canvas->fillRect(47, 29, 324, 2, lilka::colors::Black);
    canvas->fillRect(47, 33, 324, 2, lilka::colors::Black);
    canvas->fillRect(47, 37, 324, 2, lilka::colors::Black);

    // Draw title text
    canvas->setFont(FONT_5x7);
    canvas->setTextSize(2);
    canvas->setTextWrap(false);
    int16_t bigTextX1 = 0, bigTextY1 = 0;
    uint16_t bigTextWidth = 0, bigTextHeight = 0;
    canvas->setTextBound(0, 0, canvas->width(), canvas->height());   // reset clip before measuring
    canvas->getTextBounds(title, 0, 0, &bigTextX1, &bigTextY1, &bigTextWidth, &bigTextHeight);
    const uint16_t titleWidthAvailable = canvas->width() - 160;
    const uint16_t titleDrawX = canvas->width() * 0.5 - bigTextWidth * 0.5;


    if (bigTextWidth > titleWidthAvailable) {
        // Marquee
        Canvas marquee(titleWidthAvailable, titleTextHeight + 8);
        marquee.fillScreen(lilka::colors::White);
        marquee.setFont(FONT_5x7);
        marquee.setTextWrap(false);
        marquee.setTextSize(2);
        marquee.setCursor(
            calculateMarqueeShift(millis() - firstRender, bigTextWidth - titleWidthAvailable, 50), titleTextHeight
        );
        marquee.setTextColor(lilka::colors::Black);
        marquee.println(title);
        int16_t titleMarqX = canvas->width() * 0.5 - titleWidthAvailable * 0.5;
        canvas->fillRect(titleMarqX - 6, 24, titleWidthAvailable + 12, 16, lilka::colors::White);
        drawMonoCanvasTran(canvas, &marquee, canvas->width() * 0.5 - titleWidthAvailable * 0.5, 24 - bigTextHeight, titleWidthAvailable, marquee.height(), lilka::colors::White);
    } else {
        // Text fits
        canvas->setCursor(titleDrawX, 38);
        canvas->setTextColor(lilka::colors::Black);
        canvas->fillRect(titleDrawX - 6, 24, bigTextWidth + 12, 16, lilka::colors::White);
        canvas->println(title);
    }

    //     lilka::serial.log(
    //     "MENU DEBUG: title=|%s| (len=%d) titleWidthAvailable=%d bigTextWidth=%d titleDrawX=%d",
    //     title.c_str(), title.length(),
    //     titleWidthAvailable, bigTextWidth,
    //     titleDrawX
    // );

    // Highlight selected item
    constexpr int16_t highlightRadius = 7;
    canvas->fillRoundRect(
        32,
        itemsY + (cursor - scroll) * itemHeight - 0.5 * (itemHeight - menu_icon_height),
        !needsScrollbar ? canvas->width() - 64 : canvas->width() - 80, 
        itemHeight,
        highlightRadius,
        lilka::colors::Black
    );

    // Draw item icons and text
    for (int i = scroll; i < MIN(scroll + MENU_HEIGHT, menu_size); i++) {
        int16_t screenI = i - scroll;
        const menu_icon_t* icon = items[i].icon;
        canvas->setTextBound(0, itemsY + screenI * itemHeight - itemHeight, canvas->width(), itemHeight);
        
        // Draw icon if it exists
        if (icon) {
            if (cursor == i) {
                drawSelectedIcon(canvas, icon, 36, itemsY + screenI * itemHeight);
                // drawMonoIcon(canvas, icon, 34, itemsY + screenI * itemHeight);
            } else {
                drawMonoIcon(canvas, icon, 34, itemsY + screenI * itemHeight);
            }
        }

        // Draw item title, inverting text for current item
        canvas->setFont(FONT_5x7);
        canvas->setTextSize(2);
        canvas->setTextColor(cursor == i ? lilka::colors::White : lilka::colors::Black);
        canvas->setTextWrap(false);
        
        uint16_t postfixWidth = 0;
        int16_t cursorX = canvas->width() - (needsScrollbar ? 48 : 32) - 6; // position cursor 6px from rhs of highlight rect
        int16_t cursorY = itemsY + (screenI + 1) * itemHeight - 10;
        if (items[i].postfix.length()) {
            // Calculate postfix width
            int16_t x1, y1;
            uint16_t h;
            (void)x1;
            (void)y1;
            (void)h;

            canvas->getTextBounds(items[i].postfix, 0, 0, &x1, &y1, &postfixWidth, &h);
            cursorX -= postfixWidth;
            canvas->setTextBound(cursorX, cursorY, postfixWidth + 4, itemHeight);
            canvas->setCursor(cursorX, cursorY);
            canvas->println(items[i].postfix);
        }

        // lilka::serial.log(
        //     "MENU DEBUG: title=|%s| (len=%d) postfix=|%s| (len=%d) cursorX=%d cursorY=%d postfixWidth=%d",
        //     items[i].title.c_str(), items[i].title.length(),
        //     items[i].postfix.c_str(), items[i].postfix.length(),
        //     cursorX, cursorY, postfixWidth
        // );

        int16_t widthAvailable = cursorX - 58 - postfixLeftPadding;
        if (widthAvailable < 0) {
            // No space for title
            continue;
        }


                // Marquee
        // Canvas marquee(titleWidthAvailable, titleTextHeight + 8);
        // marquee.fillScreen(lilka::colors::White);
        // marquee.setFont(FONT_5x7);
        // marquee.setTextWrap(false);
        // marquee.setTextSize(2);
        // marquee.setCursor(
        //     calculateMarqueeShift(millis() - firstRender, bigTextWidth - titleWidthAvailable, 50), titleTextHeight
        // );
        // marquee.setTextColor(lilka::colors::Black);
        // marquee.println(title);
        // int16_t titleMarqX = canvas->width() * 0.5 - titleWidthAvailable * 0.5;
        // canvas->fillRect(titleMarqX - 6, 24, titleWidthAvailable + 12, 16, lilka::colors::White);
        // drawMonoCanvasTran(canvas, &marquee, 
        // canvas->width() * 0.5 - titleWidthAvailable * 0.5, 
        // 24 - bigTextHeight, 
        // titleWidthAvailable, 
        // marquee.height(), 
        // lilka::colors::White);
    

        uint16_t nameWidth = (getTextWidth(FONT_5x7, items[i].title.c_str()) + 1) * 2;
        if (nameWidth > widthAvailable && cursor == i) {
            // Marquee - only exists on cursor row, so render black-on-white
            Canvas marquee(widthAvailable, itemHeight);
            marquee.fillScreen(lilka::colors::Black);
            marquee.setFont(FONT_5x7);
            marquee.setTextWrap(false);
            marquee.setTextSize(2);
            marquee.setCursor(
                calculateMarqueeShift(millis() - lastCursorMoveUs, nameWidth - widthAvailable, 50), itemHeight
            );
            marquee.setTextColor(lilka::colors::White);
            marquee.println(items[i].title);
            drawMonoCanvasTran(
                canvas, &marquee, 70, itemsY + (screenI + 1) * itemHeight, widthAvailable, marquee.height(),
                lilka::colors::Black
            );
        } else {
            // Draw text if fits otherwise truncate
            canvas->setCursor(38 + iconWidth, itemsY + (screenI + 1) * itemHeight - 10);
            canvas->setTextBound(38 + iconWidth, itemsY + (screenI + 1) * itemHeight - 10, widthAvailable, itemHeight);

            canvas->println(items[i].title);
        }
    }

    // Draw scrollbar
    if (needsScrollbar) {
        int top = itemsY;
        int height = MENU_HEIGHT * itemHeight;
        canvas->fillRect(canvas->width() - 30, top, 2, height, lilka::colors::Black);
        canvas->fillRect(canvas->width() - 33, top, 8, 2, lilka::colors::Black);
        canvas->fillRect(canvas->width() - 33, top + height - 2, 8, 2, lilka::colors::Black);
        int barHeight = height * MENU_HEIGHT / menu_size;
        int barTop = top + scroll * height / menu_size;
        canvas->fillRect(canvas->width() - 33, barTop, 8, barHeight, lilka::colors::Black);
    }
}

bool Menu::isFinished() {
    if (done) {
        done = false;
        return true;
    }
    return false;
}

int16_t Menu::getCursor() {
    return cursor;
}

void Menu::setColor(uint16_t color) {
    this->color = color;
    // Idea is actually almost incredible, a single problem is that we can't mention default
    // color in Menu.addItem, so, maybe better not to :)
    // for (auto& item : items) {
    //     item.color = color;
    // }
}

void Menu::setBackgroundColor(uint16_t color) {
    this->bgColor = color;
}

void Menu::setLayout(MenuLayout newLayout) {
    this->layout = newLayout;
}

MenuLayout Menu::getLayout() {
    return layout;
}

bool Menu::setItem(int16_t index, const String& title, const menu_icon_t* icon, uint16_t color, const String& postfix) {
    if (index > items.size() - 1) {
        return false;
    } else {
        items[index].title = title;
        items[index].icon = icon;
        items[index].color = color;
        items[index].postfix = postfix;
        return true;
    }
}

bool Menu::getItem(int16_t index, MenuItem* menuItem) {
    if ((menuItem == NULL) || index > items.size() - 1 || index < 0) {
        return false;
    } else {
        *menuItem = items[index];
        return true;
    }
}

void Menu::clearItems() {
    setCursor(0);
    items.clear();
}

int16_t Menu::getItemCount() {
    return items.size();
}

void Menu::addActivationButton(Button activationButton) {
    // Handle if button already added
    if (std::find(activationButtons.begin(), activationButtons.end(), activationButton) != activationButtons.end())
        return;

    activationButtons.push_back(activationButton);
}

void Menu::removeActivationButton(Button activationButton) {
    activationButtons.erase(
        std::remove(activationButtons.begin(), activationButtons.end(), activationButton), activationButtons.end()
    );
}

Button Menu::getButton() {
    return button;
}

} // namespace lilka
